name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5000:5000
          - 5001:5001

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        run: docker-compose build

      - name: Run Docker containers
        run: docker-compose up -d

      - name: Wait for containers to be ready
        run: sleep 20

      - name: Test API
        run: curl -f http://localhost:5001/data

      - name: Test Web
        run: curl -f http://localhost:5000
